[package]
name = "afelus"
version = "0.1.0"
authors = ["Afel"]

[dependencies]
winapi = {version = "0.3.9", features = ["winnt","tlhelp32","handleapi","basetsd","memoryapi","handleapi","processthreadsapi","winuser"]}
